### ISSUE TITLE
rename repo

### ISSUE THREAD

**Issue by rgdonohue** [MarkCruse/smoky-mountains-trout-streams#1]
Let's consider renaming the repository to something like "smoky-mountains-fishing"?

Will look better when serving the webpage from the GitHub Pages (i.e., MarkCruse.github.io/smoky-mountains-fishing).

This can be done in the Settings of the repo itself. Then you can just rename your local folder name to be the same.

**Comment by MarkCruse** [comment]
I like that idea!  It has been done.
