### ISSUE TITLE
establish visual hierarchy for trails, roads, fishing

### ISSUE THREAD

**Issue by rgdonohue** [MarkCruse/smoky-mountains-trout-streams#4]
Fishing needs to be highlighted. Start with these areas and work the others into the background?

**Comment by MarkCruse** [comment]
I uploaded a first pass at the map.

**Comment by rgdonohue** [comment]
Great. I'll take a swing at it here shortly. See where we're at.

**Comment by rgdonohue** [comment]
Okay, I made some adjustments. Thought I had branched but accidentally pushed up to master!

Do a `git pull` on your master branch before continuing?

**Comment by MarkCruse** [comment]
I think we are good on the code now.  At first this afternoon I thought you were giving me a challenge with the conflict ;)

**Comment by rgdonohue** [comment]
We need to deal with merge conflicts at some point. :)
